# Generated by Django 5.0.2 on 2024-05-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_practice_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='event',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='band',
        ),
        migrations.RemoveField(
            model_name='bandmember',
            name='band',
        ),
        migrations.RemoveField(
            model_name='bandmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='bandmember',
            name='section',
        ),
        migrations.RemoveField(
            model_name='membersection',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membersection',
            name='section',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='BandMember',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberSection',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
