# Generated by Django 5.0.2 on 2024-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sections',
            field=models.ManyToManyField(through='display.MemberSection', to='display.section'),
        ),
    ]
