# Generated by Django 5.0.2 on 2024-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_member_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='bands',
        ),
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', through='display.BandMember', to='display.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sections',
            field=models.ManyToManyField(related_name='players', through='display.MemberSection', to='display.section'),
        ),
    ]
