# Generated by Django 5.0.2 on 2024-06-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_remove_member_bands_alter_band_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='display.event'),
        ),
    ]
