# Generated by Django 5.0.2 on 2024-05-22 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 22, 11, 1, 58, 379870, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practice',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='practice',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
