# Generated by Django 5.0.2 on 2024-05-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_practice_date_alter_practice_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='bandmember',
            name='section',
        ),
        migrations.AddField(
            model_name='bandmember',
            name='member_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='display.membersection'),
            preserve_default=False,
        ),
    ]
