# Generated by Django 5.0.2 on 2024-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_alter_membersection_proficiency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['date', 'startTime']},
        ),
    ]
